"""
AI Model Correlations Data

This module contains the MODEL_CORRELATIONS dictionary mapping AI models
to their companies, architectures, modalities, tasks, and parameters.

Data updated as of September 2026 with current public model families. Parameter
counts are marked as "undisclosed" when vendors do not publish them.
"""

from .types import ModelData


MODEL_CORRELATIONS: dict[str, ModelData] = {
    "GPT-5.5": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.5 Pro": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.6 Terra": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.6 Luna": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.6 Sol": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.6 Cyber": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-6 Astra": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-6 Sol": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-6 Luna": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.4": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.2": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.2 pro": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.3-Codex": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["code-generation", "reasoning", "agentic workflow", "professional workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5.3-Codex-Spark": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "agentic workflow", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-5 mini": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT-5 nano": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT-5": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT-4.1": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "code-generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT-4o": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "conversational", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "GPT-4": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2023,
    },
    "gpt-oss-120b": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "120B",
        "release_year": 2025,
    },
    "gpt-oss-20b": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "20B",
        "release_year": 2025,
    },
    "Sora 2 Pro": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Sora 2": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Image 2": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Image 2.5 Sunburst": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Image 2.5 Flare": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Image 1.5": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Image 1": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "DALL-E 3": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "undisclosed",
        "release_year": 2023,
    },
    "GPT-4o Transcribe": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT Transcribe": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT-4o mini TTS": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GPT Realtime 2": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime 2.1 Mini": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Live 1": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime Translate": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["translation", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime Whisper": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime 1.5": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime 2.1": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GPT Realtime": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Whisper": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "1.5B",
        "release_year": 2022,
    },
    "Claude Fable 5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Mythos 5.1": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Fable 5.1": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 5.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Sonnet 5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Sonnet 5.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 4.8": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 4.7": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 4.6": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Sonnet 4.6": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Claude Opus 4.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Sonnet 4.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Opus 4.1": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Opus 4": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Sonnet 4": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Sonnet 3.7": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Sonnet 3.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Claude 3 Opus": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Claude Haiku 4.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "conversational", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Claude Haiku 3.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Claude Haiku 3": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Gemini 3.5 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.5 Transcribe": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.5 Flash-Lite": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "multi-modal generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.1 Flash-Lite": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "multi-modal generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.8 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.8 Live": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio", "video", "text"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.8 Flash TTS": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.8 Flash-Lite TTS": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.7 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.6 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.1 Pro Preview": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.1 Flash Image": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["text-to-image", "image-to-image", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3.1 Flash-Lite Image": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["text-to-image", "image-to-image", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini 3 Pro Preview": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 3 Pro Image Preview": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-to-image", "image-to-image", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 3 Flash Preview": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 2.5 Pro": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 2.5 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 2.5 Flash Image": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["text-to-image", "image-to-image", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 2.5 Flash Live": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio", "video", "text"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 2.0 Flash-Lite": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "multi-modal generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini 1.5 Pro": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "multi-modal generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Gemini Embedding 2": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["embedding-generation", "feature-extraction"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini Robotics ER 2": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["reasoning", "image-to-text", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemini Robotics ER 1.6": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["reasoning", "image-to-text", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Gemma 4 31B": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "31B",
        "release_year": 2026,
    },
    "Gemma 4 26B": {
        "company": "Google DeepMind",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "26B total / 3.8B active",
        "release_year": 2026,
    },
    "Gemma 3 27B": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "27B",
        "release_year": 2025,
    },
    "Gemma 3n": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "multi-modal generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemma 2 27B": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "27B",
        "release_year": 2024,
    },
    "Gemma 2 9B": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "9B",
        "release_year": 2024,
    },
    "Imagen 4": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Imagen 4 Ultra": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Imagen 4 Fast": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Gemini Omni Flash Preview": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "image-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Veo 3.1": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Veo 3.1 Lite": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Lyria 3.5": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Veo 3 Fast": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Veo 2": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Muse Spark": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Muse Spark 1.3": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Llama 4 Maverick": {
        "company": "Meta AI",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "17B active / 400B total",
        "release_year": 2025,
    },
    "Llama 4 Scout": {
        "company": "Meta AI",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "17B active / 109B total",
        "release_year": 2025,
    },
    "Llama 3.3 70B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "70B",
        "release_year": 2024,
    },
    "Llama 3.1 405B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "405B",
        "release_year": 2024,
    },
    "Llama 3 70B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "70B",
        "release_year": 2024,
    },
    "Code Llama 70B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "text-generation"],
        "parameters": "70B",
        "release_year": 2024,
    },
    "ImageBind": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["image", "audio", "text", "video"],
        "tasks": ["feature-extraction", "embedding-generation"],
        "parameters": "undisclosed",
        "release_year": 2023,
    },
    "Mistral Medium 3.5": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "128B",
        "release_year": 2026,
    },
    "Mistral Small 4": {
        "company": "Mistral AI",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Mistral Large 3": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Mistral Medium 3.1": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Mistral Small 3.2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Ministral 3 14B": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "multi-modal generation"],
        "parameters": "14B",
        "release_year": 2025,
    },
    "Ministral 3 8B": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "multi-modal generation"],
        "parameters": "8B",
        "release_year": 2025,
    },
    "Ministral 3 3B": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "multi-modal generation"],
        "parameters": "3B",
        "release_year": 2025,
    },
    "Magistral Medium 1.2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Magistral Small 1.2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Devstral 2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "agentic workflow", "reasoning"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Codestral": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "text-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Mistral Nemo 12B": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "12B",
        "release_year": 2024,
    },
    "Mixtral 8x22B": {
        "company": "Mistral AI",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "141B total / 39B active",
        "release_year": 2024,
    },
    "OCR 4": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["ocr", "document-understanding", "feature-extraction"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "OCR 4.1": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["ocr", "document-understanding", "feature-extraction"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "OCR 3": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["image", "text"],
        "tasks": ["ocr", "document-understanding", "feature-extraction"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Voxtral Mini Transcribe 2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Voxtral TTS": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "4B",
        "release_year": 2026,
    },
    "Grok 4.3": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok 4.6": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok 4.7": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok 4.5": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok 4.20": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok 4": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Grok 3": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Grok Build 0.1": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "agentic workflow", "reasoning"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok Imagine Video 1.5": {
        "company": "xAI",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["image-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok Voice Think Fast 2.0": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "audio"],
        "tasks": ["conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Grok Imagine Image 2.0": {
        "company": "xAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "DeepSeek-V4-Pro": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "1.6T total / 49B active",
        "release_year": 2026,
    },
    "DeepSeek-V4-Flash": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "284B total / 13B active",
        "release_year": 2026,
    },
    "DeepSeek-V4.1-Flash": {
        "company": "DeepSeek",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "DeepSeek-V3.2": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "DeepSeek-V3.2-Speciale": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "DeepSeek-V3": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "671B",
        "release_year": 2024,
    },
    "DeepSeek-R1": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "671B",
        "release_year": 2025,
    },
    "Qwen3.7-Max": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen3.8-Max": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "2.4T total",
        "release_year": 2026,
    },
    "Qwen3.8-2.4T-A95B": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "2.4T total / 95B active",
        "release_year": 2026,
    },
    "Qwen3.8-Flash": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen3.8-27B": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "27B",
        "release_year": 2026,
    },
    "Qwen3.5-Omni": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["multi-modal generation", "conversational", "speech-to-text", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen3.8-Omni-Flash": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["multi-modal generation", "conversational", "speech-to-text"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen-Image-3.0": {
        "company": "Alibaba Cloud",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Wan3.0": {
        "company": "Alibaba Cloud",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "image-to-video", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen3.5": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "397B total / 17B active",
        "release_year": 2026,
    },
    "Qwen3-Max-Thinking": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Qwen3-Max": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Qwen3-Coder": {
        "company": "Alibaba Cloud",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["code-generation", "agentic workflow", "reasoning"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Qwen2.5-VL": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["multi-modal generation", "text-generation", "document-understanding"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Qwen2.5": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "72B",
        "release_year": 2024,
    },
    "Qwen-VL-Max": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["multi-modal generation", "document-understanding", "image-to-text"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Command A+": {
        "company": "Cohere",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "agentic workflow", "retrieval-augmented generation"],
        "parameters": "218B total / 25B active",
        "release_year": 2026,
    },
    "Command A": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "agentic workflow", "conversational"],
        "parameters": "111B",
        "release_year": 2025,
    },
    "Command A Reasoning": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Command A Vision": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "multi-modal generation", "document-understanding"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Command A Translate": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["translation", "text-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Command R7B": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "agentic workflow"],
        "parameters": "7B",
        "release_year": 2024,
    },
    "Command R+": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "agentic workflow"],
        "parameters": "104B",
        "release_year": 2024,
    },
    "Command R": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "agentic workflow"],
        "parameters": "35B",
        "release_year": 2024,
    },
    "Cohere Transcribe": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Cohere Embed v4": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["embedding-generation", "feature-extraction"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Sonar": {
        "company": "Perplexity",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "conversational"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Sonar Pro": {
        "company": "Perplexity",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "reasoning"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Sonar Reasoning Pro": {
        "company": "Perplexity",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "retrieval-augmented generation", "reasoning"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "FLUX.2 pro": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "FLUX 3": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image", "video", "audio"],
        "tasks": ["text-to-image", "image-to-image", "text-to-video", "video-generation", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "FLUX.2 dev": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "32B",
        "release_year": 2025,
    },
    "FLUX.1 Kontext max": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "FLUX.1 Kontext pro": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "FLUX.1.1 pro": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Stable Diffusion 3.5 Large": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "8B",
        "release_year": 2024,
    },
    "Stable Diffusion 3.5 Medium": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "2.5B",
        "release_year": 2024,
    },
    "Stable Diffusion XL": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2023,
    },
    "Stable Audio 3.0": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["audio"],
        "tasks": ["audio-generation"],
        "parameters": "2.7B",
        "release_year": 2026,
    },
    "Stable Audio 2.0": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["audio"],
        "tasks": ["audio-generation", "text-to-speech"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Midjourney v8": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Midjourney v8.1": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Midjourney v8.2": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Midjourney v7": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Midjourney v6.1": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Midjourney v6": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2023,
    },
    "Runway Gen-4.5": {
        "company": "Runway",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Runway Gen-4": {
        "company": "Runway",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Runway Gen-3 Alpha": {
        "company": "Runway",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Kling 3.0": {
        "company": "Kuaishou",
        "architecture": "Diffusion",
        "modality": ["video", "audio"],
        "tasks": ["text-to-video", "video-generation", "image-to-video", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Kling 2.0": {
        "company": "Kuaishou",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Pika 2.2": {
        "company": "Pika Labs",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Pika 2.0": {
        "company": "Pika Labs",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Recraft V4": {
        "company": "Recraft",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Recraft V3": {
        "company": "Recraft",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Ideogram 4.0": {
        "company": "Ideogram",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Ideogram 3.0": {
        "company": "Ideogram",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Eleven v3": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Eleven v4": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Eleven v4 Turbo": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech", "audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Eleven Music v2": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["audio-generation"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Scribe v1": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Scribe v2 Medical": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Phi-4-reasoning-vision": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["reasoning", "multi-modal generation", "document-understanding", "ocr"],
        "parameters": "15B",
        "release_year": 2026,
    },
    "Phi-4": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "14B",
        "release_year": 2025,
    },
    "Phi-4 multimodal": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio"],
        "tasks": ["text-generation", "multi-modal generation", "speech-to-text"],
        "parameters": "5.6B",
        "release_year": 2025,
    },
    "Phi-4-mini": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "3.8B",
        "release_year": 2025,
    },
    "Phi-3": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "3.8B",
        "release_year": 2024,
    },
    "Jamba 1.6 Large": {
        "company": "AI21 Labs",
        "architecture": "Hybrid Transformer-SSM",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "retrieval-augmented generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Jamba 1.6 Mini": {
        "company": "AI21 Labs",
        "architecture": "Hybrid Transformer-SSM",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "retrieval-augmented generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "GLM-5.2": {
        "company": "Zhipu AI",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "753B total / 40B active",
        "release_year": 2026,
    },
    "GLM-5.3": {
        "company": "Zhipu AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "GLM-5": {
        "company": "Zhipu AI",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "744B total / 40B active",
        "release_year": 2026,
    },
    "GLM-4.5": {
        "company": "Zhipu AI",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Kimi K2.6": {
        "company": "Moonshot AI",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "1T total / 32B active",
        "release_year": 2026,
    },
    "Kimi K3": {
        "company": "Moonshot AI",
        "architecture": "Transformer",
        "modality": ["text", "image", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "undisclosed",
        "release_year": 2026,
    },
    "Yi-Lightning": {
        "company": "01.AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2024,
    },
    "Ernie 4.5": {
        "company": "Baidu",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Doubao 1.5 Pro": {
        "company": "ByteDance",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Hunyuan Turbo S": {
        "company": "Tencent",
        "architecture": "Mixture of Experts",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "undisclosed",
        "release_year": 2025,
    },
    "Falcon 3": {
        "company": "TII",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "10B",
        "release_year": 2024,
    },
    "Falcon 180B": {
        "company": "TII",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation"],
        "parameters": "180B",
        "release_year": 2023,
    },
    "Mamba 2": {
        "company": "Cartesia",
        "architecture": "State Space",
        "modality": ["text"],
        "tasks": ["text-generation", "sequence-modeling"],
        "parameters": "8B",
        "release_year": 2024,
    },
    "RWKV-7": {
        "company": "RWKV Foundation",
        "architecture": "Recurrent Neural Network",
        "modality": ["text"],
        "tasks": ["text-generation", "sequence-modeling"],
        "parameters": "14B",
        "release_year": 2025,
    },
    "StarCoder 2": {
        "company": "Hugging Face",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "text-generation"],
        "parameters": "15B",
        "release_year": 2024,
    },
    "T5": {
        "company": "Google",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "translation", "summarization"],
        "parameters": "11B",
        "release_year": 2020,
    },
    "BERT": {
        "company": "Google",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["classification", "feature-extraction", "embedding-generation"],
        "parameters": "340M",
        "release_year": 2018,
    },
    "RoBERTa": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["classification", "feature-extraction", "embedding-generation"],
        "parameters": "355M",
        "release_year": 2019,
    },
}
