"""
AI Model Correlations Data

This module contains the MODEL_CORRELATIONS dictionary mapping AI models
to their companies, architectures, modalities, tasks, and parameters.

Data updated as of February 2026 with latest model releases.
"""

from .types import ModelData


MODEL_CORRELATIONS: dict[str, ModelData] = {
    "GPT-5.2": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "1.5T",
        "release_year": 2026,
    },
    "GPT-5": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "1T",
        "release_year": 2025,
    },
    "GPT-5.3-Codex": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "reasoning", "agentic workflow"],
        "parameters": "500B",
        "release_year": 2026,
    },
    "GPT-4o": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio"],
        "tasks": ["text-generation", "conversational", "multi-modal generation"],
        "parameters": "200B",
        "release_year": 2024,
    },
    "GPT-4": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "175B",
        "release_year": 2023,
    },
    "DALL-E 4": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "12B",
        "release_year": 2025,
    },
    "DALL-E 3": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "8B",
        "release_year": 2023,
    },
    "Sora 2": {
        "company": "OpenAI",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation"],
        "parameters": "50B",
        "release_year": 2026,
    },
    "Whisper": {
        "company": "OpenAI",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["speech-to-text", "audio-classification"],
        "parameters": "1.5B",
        "release_year": 2022,
    },
    "Claude Opus 4.6": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "1T",
        "release_year": 2026,
    },
    "Claude Sonnet 4.5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "conversational"],
        "parameters": "400B",
        "release_year": 2026,
    },
    "Claude 5": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow", "multi-modal generation"],
        "parameters": "1.5T",
        "release_year": 2026,
    },
    "Claude 3.7 Sonnet": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "200B",
        "release_year": 2025,
    },
    "Claude 3.5 Sonnet": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "175B",
        "release_year": 2024,
    },
    "Claude 3 Opus": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "175B",
        "release_year": 2024,
    },
    "Claude 3 Haiku": {
        "company": "Anthropic",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "conversational"],
        "parameters": "20B",
        "release_year": 2024,
    },
    "Gemini 3 Pro": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation", "code-generation"],
        "parameters": "1T",
        "release_year": 2025,
    },
    "Gemini 3 Flash": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "200B",
        "release_year": 2026,
    },
    "Gemini 3 Deep Think": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["reasoning", "text-generation", "code-generation"],
        "parameters": "1.5T",
        "release_year": 2026,
    },
    "Gemini 2.5 Pro": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "500B",
        "release_year": 2025,
    },
    "Gemini 1.5 Pro": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text", "image", "audio", "video"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "175B",
        "release_year": 2024,
    },
    "Gemma 3": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "27B",
        "release_year": 2026,
    },
    "Gemma 2": {
        "company": "Google DeepMind",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "9B",
        "release_year": 2024,
    },
    "Imagen 4": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "20B",
        "release_year": 2025,
    },
    "Veo 2": {
        "company": "Google DeepMind",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation"],
        "parameters": "30B",
        "release_year": 2025,
    },
    "LLaMA 4": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "500B",
        "release_year": 2026,
    },
    "LLaMA 4.1": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "agentic workflow"],
        "parameters": "600B",
        "release_year": 2026,
    },
    "LLaMA 3.1 405B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "405B",
        "release_year": 2024,
    },
    "LLaMA 3 70B": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "70B",
        "release_year": 2024,
    },
    "CodeLlama 3": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "text-generation"],
        "parameters": "70B",
        "release_year": 2025,
    },
    "ImageBind 2": {
        "company": "Meta AI",
        "architecture": "Transformer",
        "modality": ["image", "audio", "text", "video"],
        "tasks": ["feature-extraction", "embedding-generation"],
        "parameters": "7B",
        "release_year": 2025,
    },
    "Mistral Large 3": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "123B",
        "release_year": 2025,
    },
    "Mistral Nemo 2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "12B",
        "release_year": 2025,
    },
    "Pixtral 2": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "image-to-text", "multi-modal generation"],
        "parameters": "24B",
        "release_year": 2026,
    },
    "Mixtral 8x22B": {
        "company": "Mistral AI",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "176B",
        "release_year": 2024,
    },
    "Codestral": {
        "company": "Mistral AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "text-generation"],
        "parameters": "22B",
        "release_year": 2024,
    },
    "Grok-5": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "conversational"],
        "parameters": "800B",
        "release_year": 2026,
    },
    "Grok-4": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational"],
        "parameters": "400B",
        "release_year": 2025,
    },
    "Grok-3": {
        "company": "xAI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "conversational"],
        "parameters": "200B",
        "release_year": 2024,
    },
    "DeepSeek-V4": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "800B",
        "release_year": 2026,
    },
    "DeepSeek-V3": {
        "company": "DeepSeek",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "671B",
        "release_year": 2025,
    },
    "DeepSeek-Coder-V3": {
        "company": "DeepSeek",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation", "reasoning"],
        "parameters": "236B",
        "release_year": 2025,
    },
    "Qwen3": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation", "multi-modal generation"],
        "parameters": "110B",
        "release_year": 2025,
    },
    "Qwen2.5": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "72B",
        "release_year": 2024,
    },
    "Qwen-VL-Max": {
        "company": "Alibaba Cloud",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["image-to-text", "multi-modal generation"],
        "parameters": "72B",
        "release_year": 2024,
    },
    "Command R2": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "conversational"],
        "parameters": "150B",
        "release_year": 2026,
    },
    "Command R+": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "conversational"],
        "parameters": "104B",
        "release_year": 2024,
    },
    "Cohere Embed v4": {
        "company": "Cohere",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["embedding-generation", "feature-extraction"],
        "parameters": "1B",
        "release_year": 2025,
    },
    "Flux Pro 2": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "25B",
        "release_year": 2026,
    },
    "Flux Pro": {
        "company": "Black Forest Labs",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "12B",
        "release_year": 2024,
    },
    "Stable Diffusion 4": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "15B",
        "release_year": 2025,
    },
    "Stable Diffusion XL": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image", "image-to-image"],
        "parameters": "6.6B",
        "release_year": 2023,
    },
    "Stable Video Diffusion 2": {
        "company": "Stability AI",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation"],
        "parameters": "10B",
        "release_year": 2025,
    },
    "Midjourney v7": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "unknown",
        "release_year": 2025,
    },
    "Midjourney v6": {
        "company": "Midjourney",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "unknown",
        "release_year": 2024,
    },
    "GLM-5": {
        "company": "Zhipu AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "200B",
        "release_year": 2026,
    },
    "GLM-4V": {
        "company": "Zhipu AI",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "image-to-text"],
        "parameters": "130B",
        "release_year": 2024,
    },
    "Yi-Lightning": {
        "company": "01.AI",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning"],
        "parameters": "200B",
        "release_year": 2024,
    },
    "StarCoder 3": {
        "company": "Hugging Face",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation"],
        "parameters": "25B",
        "release_year": 2025,
    },
    "StarCoder 2": {
        "company": "Hugging Face",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["code-generation"],
        "parameters": "15B",
        "release_year": 2024,
    },
    "Phi-4": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning", "code-generation"],
        "parameters": "14B",
        "release_year": 2025,
    },
    "Phi-3": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning"],
        "parameters": "3.8B",
        "release_year": 2024,
    },
    "Copilot Pro 2026": {
        "company": "Microsoft",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["code-generation", "text-generation", "agentic workflow"],
        "parameters": "175B",
        "release_year": 2026,
    },
    "Falcon 3": {
        "company": "TII",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation", "code-generation"],
        "parameters": "200B",
        "release_year": 2025,
    },
    "Falcon 180B": {
        "company": "TII",
        "architecture": "Transformer",
        "modality": ["text"],
        "tasks": ["text-generation"],
        "parameters": "180B",
        "release_year": 2023,
    },
    "BERT": {
        "company": "Google",
        "architecture": "Encoder-Only",
        "modality": ["text"],
        "tasks": ["text-classification", "fill-mask", "named-entity-recognition"],
        "parameters": "340M",
        "release_year": 2018,
    },
    "RoBERTa": {
        "company": "Meta AI",
        "architecture": "Encoder-Only",
        "modality": ["text"],
        "tasks": ["text-classification", "fill-mask", "named-entity-recognition"],
        "parameters": "355M",
        "release_year": 2019,
    },
    "T5": {
        "company": "Google",
        "architecture": "Encoder-Decoder",
        "modality": ["text"],
        "tasks": ["text-generation", "translation", "summarization"],
        "parameters": "11B",
        "release_year": 2020,
    },
    "Mamba 2": {
        "company": "Cartesia",
        "architecture": "State Space Model",
        "modality": ["text"],
        "tasks": ["text-generation"],
        "parameters": "8B",
        "release_year": 2024,
    },
    "RWKV-7": {
        "company": "RWKV Foundation",
        "architecture": "RWKV",
        "modality": ["text"],
        "tasks": ["text-generation"],
        "parameters": "14B",
        "release_year": 2025,
    },
    "ElevenLabs Turbo v3": {
        "company": "ElevenLabs",
        "architecture": "Transformer",
        "modality": ["audio"],
        "tasks": ["text-to-speech"],
        "parameters": "2B",
        "release_year": 2025,
    },
    "Kling 2.0": {
        "company": "Kuaishou",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation"],
        "parameters": "50B",
        "release_year": 2026,
    },
    "Runway Gen-4": {
        "company": "Runway",
        "architecture": "Diffusion",
        "modality": ["video", "image"],
        "tasks": ["text-to-video", "video-generation", "image-to-video"],
        "parameters": "20B",
        "release_year": 2026,
    },
    "Pika 2.0": {
        "company": "Pika Labs",
        "architecture": "Diffusion",
        "modality": ["video"],
        "tasks": ["text-to-video", "video-generation"],
        "parameters": "15B",
        "release_year": 2025,
    },
    "Recraft V3": {
        "company": "Recraft",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "8B",
        "release_year": 2024,
    },
    "Ideogram 3": {
        "company": "Ideogram",
        "architecture": "Diffusion",
        "modality": ["image"],
        "tasks": ["text-to-image"],
        "parameters": "10B",
        "release_year": 2025,
    },
    "Jamba 2": {
        "company": "AI21 Labs",
        "architecture": "Hybrid Model",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning"],
        "parameters": "250B",
        "release_year": 2025,
    },
    "Ernie 5.0": {
        "company": "Baidu",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "multi-modal generation"],
        "parameters": "500B",
        "release_year": 2025,
    },
    "Doubao Pro": {
        "company": "ByteDance",
        "architecture": "Transformer",
        "modality": ["text", "image"],
        "tasks": ["text-generation", "reasoning", "multi-modal generation"],
        "parameters": "300B",
        "release_year": 2025,
    },
    "Hunyuan-Large": {
        "company": "Tencent",
        "architecture": "Mixture of Experts",
        "modality": ["text"],
        "tasks": ["text-generation", "reasoning"],
        "parameters": "400B",
        "release_year": 2024,
    },
}
